<a href="https://colab.research.google.com/github/Yasasvi2025/Mini-Project-Student-Performance-Analytics-System-Python-with-AI/blob/main/Mini_Project_Student_Performance_Analytics_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Student Performance Analytics System

**Python with AI – Mini Project**

**Project Title:** Student Performance Analytics System

**Technologies Used:** Python, NumPy, Pandas

**Concepts Covered:** Variables, Data Types, Conditional Statements, Loops, Functions, NumPy, Pandas, Data Analysis, Data Visualization, and Statistical Analysis.

**Project Description:**

The Student Performance Analytics System is a Python-based mini project designed to analyze student academic performance using marks, attendance, and department information. It calculates total and average marks, assigns grades, identifies pass/fail results, analyzes subject-wise and department-wise performance, and identifies top-performing students. The project uses NumPy and Pandas to process data and generate meaningful insights from the student dataset.

## **Code 1: Import Libraries and Load Dataset**

In [27]:
# ================================================================
# CODE 1: IMPORT LIBRARIES AND LOAD DATASET
# ================================================================

import os
import glob
import numpy as np
import pandas as pd
from IPython.display import display

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 150)

# Search common dataset names in the current folder and Google Colab folder.
possible_names = [
    "student.csv",
    "students.csv",
    "student(1).csv",
    "student_data.csv",
    "students_data.csv",
]
search_dirs = [os.getcwd(), "/content"]
possible_files = [
    os.path.join(folder, name)
    for folder in search_dirs
    for name in possible_names
]

CSV_FILE = next(
    (path for path in possible_files if os.path.isfile(path)),
    None
)

# If a common filename was not found, look for another CSV in the folder,
# excluding the report generated by this notebook.
if CSV_FILE is None:
    other_csv_files = sorted(
        path for folder in search_dirs if os.path.isdir(folder)
        for path in glob.glob(os.path.join(folder, "*.csv"))
        if os.path.basename(path).lower() != "student_performance_analysis.csv"
    )
    if other_csv_files:
        CSV_FILE = other_csv_files[0]

# If no CSV is found, ask the user to upload one in Google Colab.
if CSV_FILE is None:
    try:
        from google.colab import files
        print("No student CSV found. Please upload your student dataset:")
        uploaded = files.upload()
        csv_files = [name for name in uploaded if name.lower().endswith(".csv")]
        if not csv_files:
            raise FileNotFoundError("Please upload a CSV file.")
        CSV_FILE = csv_files[0]
    except ImportError as exc:
        raise FileNotFoundError(
            "No CSV dataset found. Place student.csv, students.csv, "
            "student(1).csv, or another student dataset CSV in the notebook folder."
        ) from exc

print("CSV file selected:", os.path.basename(CSV_FILE))
data = pd.read_csv(CSV_FILE)

print("STUDENT PERFORMANCE ANALYTICS SYSTEM")
print("-" * 60)
print("Dataset loaded successfully!")
print("Number of records:", len(data))
print("Number of columns:", len(data.columns))

display(data)

CSV file selected: student.csv
STUDENT PERFORMANCE ANALYTICS SYSTEM
------------------------------------------------------------
Dataset loaded successfully!
Number of records: 30
Number of columns: 9

    Student_ID     Name Department  Python  SQL  HTML  CSS  JavaScript  Attendance
0          101   Anjali        CSE      85   78    90   88          82          92
1          102    Rahul        CSE      72   80    75   70          78          85
2          103    Sneha         IT      95   92    88   94          96          98
3          104    Arjun        CSE      60   65    58   62          70          75
4          105    Priya         IT      88   85    91   89          90          94
5          106    Kiran        ECE      76   74    80   78          82          88
6          107    Meena        CSE      92   89    95   91          94          96
7          108   Vikram         IT      68   72    65   70          74          82
8          109    Divya        ECE      81   79    85   83          87          90
9          110    Rohit        CSE      55   62    58   60          65          78
10         111    Kavya         IT      90   94    89   92          91          97
11         112   Aditya        CSE      73   69    76   72          78          84
12         113     Neha        ECE      86   88    84   87          85          93
13         114    Manoj         IT      48   55    52   50          58          76
14         115    Pooja        CSE      79   82    80   77          84          89
15         116    Akash        ECE      64   60    68   65          70          80
16         117     Isha         IT      93   90    92   95          94          98
17         118    Varun        CSE      58   61    55   59          63          74
18         119     Riya        ECE      84   86    82   88          89          91
19         120   Sanjay         IT      70   75    72   74          76          86
20         121    Aarav        CSE      82   85    79   84          88          91
21         122   Simran         IT      91   87    93   90          89          95
22         123   Harish        ECE      67   71    69   73          75          83
23         124    Nisha        CSE      89   92    86   88          91          96
24         125    Varun         IT      74   78    72   76          80          87
25         126   Swathi        ECE      96   94    91   93          95          99
26         127   Manish        CSE      63   68    61   65          70          79
27         128  Keerthi         IT      85   83    88   86          90          92
28         129   Rakesh        ECE      77   75    81   79          84          89
29         130    Aditi        CSE      94   91    96   92          93          97

## **Code 2: Validate the Dataset**

In [28]:
# ================================================================
# CODE 2: DATASET VALIDATION
# ================================================================

required_columns = [
    "Student_ID", "Name", "Department",
    "Python", "SQL", "HTML", "CSS",
    "JavaScript", "Attendance"
]

missing_columns = [
    col for col in required_columns
    if col not in data.columns
]

if missing_columns:
    raise ValueError(
        f"Missing required columns: {missing_columns}"
    )

if data.empty:
    raise ValueError("The dataset is empty.")

if data["Student_ID"].isna().any():
    raise ValueError("Student_ID contains missing values.")

if data["Student_ID"].duplicated().any():
    raise ValueError("Duplicate Student_ID values found.")

if data["Name"].isna().any() or data["Department"].isna().any():
    raise ValueError("Name or Department contains missing values.")

subjects = [
    "Python", "SQL", "HTML", "CSS", "JavaScript"
]

for column in subjects + ["Attendance"]:
    data[column] = pd.to_numeric(
        data[column], errors="raise"
    )

if data[subjects + ["Attendance"]].isna().any().any():
    raise ValueError(
        "Missing marks or attendance values found."
    )

for column in subjects + ["Attendance"]:
    if not data[column].between(0, 100).all():
        raise ValueError(
            f"{column} must contain values between 0 and 100."
        )

print("Dataset validation completed successfully.")
print("Number of students:", len(data))
print("Number of subjects:", len(subjects))
print("Missing values:", int(data[required_columns].isna().sum().sum()))

print("\nDataset information:")
data.info()

print("\nStatistical summary:")
display(data[subjects + ["Attendance"]].describe().round(2))

Dataset validation completed successfully.
Number of students: 30
Number of subjects: 5
Missing values: 0

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  30 non-null     int64
 1   Name        30 non-null     object
 2   Department  30 non-null     object
 3   Python      30 non-null     int64
 4   SQL         30 non-null     int64
 5   HTML        30 non-null     int64
 6   CSS         30 non-null     int64
 7   JavaScript  30 non-null     int64
 8   Attendance  30 non-null     int64
dtypes: int64(7), object(2)
memory usage: 2.2+ KB

Statistical summary:

       Python    SQL   HTML    CSS  JavaScript  Attendance
count   30.00  30.00  30.00  30.00       30.00       30.00
mean    77.83  78.67  78.37  79.00       82.03       88.47
std     13.12  11.11  12.79  12.24       10.31        7.46
min     48.00  55.00  52.00  50.00       58.00       74.00
25%     68.50  71.25  69.75  70.50       75.25       83.25
50%     80.00  79.50  80.50  81.00       84.00       89.50
75%     88.75  87.75  88.75  88.75       90.00       94.75
max     96.00  94.00  96.00  95.00       96.00       99.00

## **Code 3: Define Reusable Functions**

In [29]:
# ================================================================
# CODE 3: REUSABLE FUNCTIONS
# ================================================================

PASS_MARK = 40

def calculate_total(row):
    """Calculate total marks across all subjects."""
    return sum(row[subject] for subject in subjects)


def calculate_average(row):
    """Calculate average marks."""
    return calculate_total(row) / len(subjects)


def assign_grade(average):
    """Assign a grade based on average marks."""
    if average >= 90:
        return "A+"
    elif average >= 80:
        return "A"
    elif average >= 70:
        return "B"
    elif average >= 60:
        return "C"
    elif average >= 50:
        return "D"
    else:
        return "F"


def check_result(row):
    """Pass if every subject mark is at least 40 and attendance is at least 75%."""
    for subject in subjects:
        if row[subject] < PASS_MARK:
            return "Fail"
    if row["Attendance"] < 75:
        return "Fail"
    return "Pass"


def get_performance_level(average):
    """Classify overall student performance."""
    if average >= 90:
        return "Excellent"
    elif average >= 75:
        return "Very Good"
    elif average >= 60:
        return "Good"
    elif average >= 40:
        return "Average"
    else:
        return "Needs Improvement"


def show_section(title):
    """Display a formatted section heading."""
    print("\n" + "=" * 70)
    print(title)
    print("=" * 70)


print("All reusable functions defined successfully.")

All reusable functions defined successfully.

## **Code 4: Calculate Student Totals, Averages, Grades and Results**

In [30]:
# ================================================================
# CODE 4: STUDENT PERFORMANCE CALCULATIONS
# ================================================================

analysis = data.copy()

analysis["Total_Marks"] = analysis.apply(
    calculate_total, axis=1
)

analysis["Average_Marks"] = analysis.apply(
    calculate_average, axis=1
)

analysis["Grade"] = analysis["Average_Marks"].apply(
    assign_grade
)

analysis["Result"] = analysis.apply(
    check_result, axis=1
)

analysis["Performance"] = analysis["Average_Marks"].apply(
    get_performance_level
)

analysis["Average_Marks"] = analysis["Average_Marks"].round(2)

show_section("STUDENT PERFORMANCE RESULTS")

result_columns = [
    "Student_ID", "Name", "Department",
    "Total_Marks", "Average_Marks",
    "Grade", "Result", "Attendance", "Performance"
]

display(
    analysis[result_columns]
    .sort_values("Student_ID")
    .reset_index(drop=True)
)

======================================================================
STUDENT PERFORMANCE RESULTS
======================================================================

    Student_ID     Name Department  Total_Marks  Average_Marks Grade Result  Attendance Performance
0          101   Anjali        CSE          423           84.6     A   Pass          92   Very Good
1          102    Rahul        CSE          375           75.0     B   Pass          85   Very Good
2          103    Sneha         IT          465           93.0    A+   Pass          98   Excellent
3          104    Arjun        CSE          315           63.0     C   Pass          75        Good
4          105    Priya         IT          443           88.6     A   Pass          94   Very Good
5          106    Kiran        ECE          390           78.0     B   Pass          88   Very Good
6          107    Meena        CSE          461           92.2    A+   Pass          96   Excellent
7          108   Vikram         IT          349           69.8     C   Pass          82        Good
8          109    Divya        ECE          415           83.0     A   Pass          90   Very Good
9          110    Rohit        CSE          300           60.0     C   Pass          78        Good
10         111    Kavya         IT          456           91.2    A+   Pass          97   Excellent
11         112   Aditya        CSE          368           73.6     B   Pass          84        Good
12         113     Neha        ECE          430           86.0     A   Pass          93   Very Good
13         114    Manoj         IT          263           52.6     D   Pass          76     Average
14         115    Pooja        CSE          402           80.4     A   Pass          89   Very Good
15         116    Akash        ECE          327           65.4     C   Pass          80        Good
16         117     Isha         IT          464           92.8    A+   Pass          98   Excellent
17         118    Varun        CSE          296           59.2     D   Fail          74     Average
18         119     Riya        ECE          429           85.8     A   Pass          91   Very Good
19         120   Sanjay         IT          367           73.4     B   Pass          86        Good
20         121    Aarav        CSE          418           83.6     A   Pass          91   Very Good
21         122   Simran         IT          450           90.0    A+   Pass          95   Excellent
22         123   Harish        ECE          355           71.0     B   Pass          83        Good
23         124    Nisha        CSE          446           89.2     A   Pass          96   Very Good
24         125    Varun         IT          380           76.0     B   Pass          87   Very Good
25         126   Swathi        ECE          469           93.8    A+   Pass          99   Excellent
26         127   Manish        CSE          327           65.4     C   Pass          79        Good
27         128  Keerthi         IT          432           86.4     A   Pass          92   Very Good
28         129   Rakesh        ECE          396           79.2     B   Pass          89   Very Good
29         130    Aditi        CSE          466           93.2    A+   Pass          97   Excellent

## **Code 5: Overall Class Performance**

In [31]:
# ================================================================
# CODE 5: OVERALL CLASS PERFORMANCE
# ================================================================

total_students = len(analysis)

class_average = analysis["Average_Marks"].mean()
highest_average = analysis["Average_Marks"].max()
lowest_average = analysis["Average_Marks"].min()

highest_student = analysis.loc[
    analysis["Average_Marks"].idxmax()
]

lowest_student = analysis.loc[
    analysis["Average_Marks"].idxmin()
]

total_passed = int(
    (analysis["Result"] == "Pass").sum()
)

total_failed = int(
    (analysis["Result"] == "Fail").sum()
)

pass_percentage = total_passed / total_students * 100
fail_percentage = total_failed / total_students * 100

show_section("OVERALL CLASS PERFORMANCE")

print("Total students:", total_students)
print(f"Class average: {class_average:.2f}")
print(f"Highest average: {highest_average:.2f}")
print(f"Lowest average: {lowest_average:.2f}")

print(
    f"Top performer: {highest_student['Name']} "
    f"(ID: {highest_student['Student_ID']})"
)

print(
    f"Lowest performer: {lowest_student['Name']} "
    f"(ID: {lowest_student['Student_ID']})"
)

print("Students passed:", total_passed)
print("Students failed:", total_failed)
print(f"Pass percentage: {pass_percentage:.2f}%")
print(f"Fail percentage: {fail_percentage:.2f}%")

======================================================================
OVERALL CLASS PERFORMANCE
======================================================================
Total students: 30
Class average: 79.18
Highest average: 93.80
Lowest average: 52.60
Top performer: Swathi (ID: 126)
Lowest performer: Manoj (ID: 114)
Students passed: 29
Students failed: 1
Pass percentage: 96.67%
Fail percentage: 3.33%

## **Code 6: Subject-Wise Performance Analysis**

In [32]:
# ================================================================
# CODE 6: SUBJECT-WISE PERFORMANCE ANALYSIS
# ================================================================

subject_summary = pd.DataFrame({
    "Subject": subjects,
    "Average_Marks": [
        data[subject].mean() for subject in subjects
    ],
    "Highest_Marks": [
        data[subject].max() for subject in subjects
    ],
    "Lowest_Marks": [
        data[subject].min() for subject in subjects
    ],
    "Students_Passed": [
        int((data[subject] >= PASS_MARK).sum())
        for subject in subjects
    ],
    "Students_Failed": [
        int((data[subject] < PASS_MARK).sum())
        for subject in subjects
    ]
})

subject_summary["Average_Marks"] = (
    subject_summary["Average_Marks"].round(2)
)

show_section("SUBJECT-WISE PERFORMANCE")

subject_summary = subject_summary.sort_values(
    "Average_Marks", ascending=False
).reset_index(drop=True)

display(subject_summary)

best_subject = subject_summary.iloc[0]
weakest_subject = subject_summary.iloc[-1]

print(
    f"Best subject: {best_subject['Subject']} "
    f"({best_subject['Average_Marks']:.2f})"
)

print(
    f"Lowest-average subject: {weakest_subject['Subject']} "
    f"({weakest_subject['Average_Marks']:.2f})"
)

======================================================================
SUBJECT-WISE PERFORMANCE
======================================================================

      Subject  Average_Marks  Highest_Marks  Lowest_Marks  Students_Passed  Students_Failed
0  JavaScript          82.03             96            58               30                0
1         CSS          79.00             95            50               30                0
2         SQL          78.67             94            55               30                0
3        HTML          78.37             96            52               30                0
4      Python          77.83             96            48               30                0

Best subject: JavaScript (82.03)
Lowest-average subject: Python (77.83)

## **Code 7: Identify Top Five Students**

In [33]:
# ================================================================
# CODE 7: TOP FIVE PERFORMERS
# ================================================================

show_section("TOP FIVE PERFORMING STUDENTS")

top_students = analysis.sort_values(
    by=["Average_Marks", "Total_Marks"],
    ascending=[False, False]
).head(5)

display(
    top_students[
        [
            "Student_ID", "Name", "Department",
            "Total_Marks", "Average_Marks",
            "Grade", "Result"
        ]
    ].reset_index(drop=True)
)

======================================================================
TOP FIVE PERFORMING STUDENTS
======================================================================

   Student_ID    Name Department  Total_Marks  Average_Marks Grade Result
0         126  Swathi        ECE          469           93.8    A+   Pass
1         130   Aditi        CSE          466           93.2    A+   Pass
2         103   Sneha         IT          465           93.0    A+   Pass
3         117    Isha         IT          464           92.8    A+   Pass
4         107   Meena        CSE          461           92.2    A+   Pass

## **Code 8: Department-Wise Performance**

In [34]:
# ================================================================
# CODE 8: DEPARTMENT-WISE PERFORMANCE
# ================================================================

department_summary = analysis.groupby("Department").agg(
    Student_Count=("Student_ID", "count"),
    Average_Marks=("Average_Marks", "mean"),
    Average_Attendance=("Attendance", "mean"),
    Students_Passed=(
        "Result", lambda x: (x == "Pass").sum()
    ),
    Students_Failed=(
        "Result", lambda x: (x == "Fail").sum()
    )
).reset_index()

department_summary["Average_Marks"] = (
    department_summary["Average_Marks"].round(2)
)

department_summary["Average_Attendance"] = (
    department_summary["Average_Attendance"].round(2)
)

show_section("DEPARTMENT-WISE PERFORMANCE")

department_summary = department_summary.sort_values(
    "Average_Marks", ascending=False
).reset_index(drop=True)

display(department_summary)

best_department = department_summary.iloc[0]

print(
    f"Highest-average department: "
    f"{best_department['Department']} "
    f"({best_department['Average_Marks']:.2f})"
)

======================================================================
DEPARTMENT-WISE PERFORMANCE
======================================================================

  Department  Student_Count  Average_Marks  Average_Attendance  Students_Passed  Students_Failed
0         IT             10          81.38               90.50               10                0
1        ECE              8          80.28               89.12                8                0
2        CSE             12          76.62               86.33               11                1

Highest-average department: IT (81.38)

## **Code 9: Grade Distribution**

In [35]:
# ================================================================
# CODE 9: GRADE DISTRIBUTION
# ================================================================

grade_order = ["A+", "A", "B", "C", "D", "F"]

grade_counts = (
    analysis["Grade"]
    .value_counts()
    .reindex(grade_order, fill_value=0)
)

grade_summary = pd.DataFrame({
    "Grade": grade_order,
    "Number_of_Students": [
        int(grade_counts[grade]) for grade in grade_order
    ]
})

grade_summary["Percentage"] = (
    grade_summary["Number_of_Students"]
    / total_students * 100
).round(2)

show_section("GRADE DISTRIBUTION")

display(grade_summary)

======================================================================
GRADE DISTRIBUTION
======================================================================

  Grade  Number_of_Students  Percentage
0    A+                   7       23.33
1     A                   9       30.00
2     B                   7       23.33
3     C                   5       16.67
4     D                   2        6.67
5     F                   0        0.00

## **Code 10: Attendance Analysis**

In [36]:
# ================================================================
# CODE 10: ATTENDANCE ANALYSIS
# ================================================================

show_section("ATTENDANCE ANALYSIS")

average_attendance = data["Attendance"].mean()

attendance_eligible = int(
    (data["Attendance"] >= 75).sum()
)

attendance_below_75 = int(
    (data["Attendance"] < 75).sum()
)

print(f"Average attendance: {average_attendance:.2f}%")
print(f"Students with attendance >= 75%: {attendance_eligible}")
print(f"Students with attendance < 75%: {attendance_below_75}")

print("\nStudents with attendance below 75%:")

low_attendance = analysis.loc[
    analysis["Attendance"] < 75,
    ["Student_ID", "Name", "Department", "Attendance"]
]

if low_attendance.empty:
    print("No students have attendance below 75%.")
else:
    display(low_attendance.reset_index(drop=True))

======================================================================
ATTENDANCE ANALYSIS
======================================================================
Average attendance: 88.47%
Students with attendance >= 75%: 29
Students with attendance < 75%: 1

Students with attendance below 75%:

   Student_ID   Name Department  Attendance
0         118  Varun        CSE          74

## **Code 11: NumPy Numerical Analysis**

In [37]:
# ================================================================
# CODE 11: NUMPY NUMERICAL ANALYSIS
# ================================================================

show_section("NUMPY NUMERICAL ANALYSIS")

marks_array = data[subjects].to_numpy(dtype=float)

print("NumPy array shape:", marks_array.shape)
print("Total subject marks:", np.sum(marks_array))
print("Mean of subject marks:", round(float(np.mean(marks_array)), 2))
print("Median of subject marks:", round(float(np.median(marks_array)), 2))
print(
    "Standard deviation:",
    round(float(np.std(marks_array)), 2)
)

numpy_subject_averages = np.mean(marks_array, axis=0)

print("\nSubject averages calculated using NumPy:")

for index in range(len(subjects)):
    print(
        f"{subjects[index]}: "
        f"{numpy_subject_averages[index]:.2f}"
    )

======================================================================
NUMPY NUMERICAL ANALYSIS
======================================================================
NumPy array shape: (30, 5)
Total subject marks: 11877.0
Mean of subject marks: 79.18
Median of subject marks: 81.5
Standard deviation: 11.85

Subject averages calculated using NumPy:
Python: 77.83
SQL: 78.67
HTML: 78.37
CSS: 79.00
JavaScript: 82.03

## **Code 12: Key Findings and Recommendations**

In [38]:
# ================================================================
# CODE 12: KEY FINDINGS AND RECOMMENDATIONS
# ================================================================

show_section("KEY FINDINGS AND RECOMMENDATIONS")

print(f"1. Overall class average: {class_average:.2f}")

print(
    f"2. {total_passed} out of {total_students} students passed "
    f"all subjects."
)

print(
    f"3. Best-performing subject: {best_subject['Subject']}."
)

print(
    f"4. Lowest-average subject: {weakest_subject['Subject']}."
)

if weakest_subject["Average_Marks"] < class_average:
    print(
        f"5. Recommendation: Provide additional practice "
        f"in {weakest_subject['Subject']}."
    )
else:
    print(
        "5. Recommendation: Continue monitoring subject performance."
    )

if attendance_below_75 > 0:
    print(
        f"6. Recommendation: Follow up with "
        f"{attendance_below_75} student(s) below 75% attendance."
    )
else:
    print("6. All students have attendance of at least 75%.")

======================================================================
KEY FINDINGS AND RECOMMENDATIONS
======================================================================
1. Overall class average: 79.18
2. 29 out of 30 students passed all subjects.
3. Best-performing subject: JavaScript.
4. Lowest-average subject: Python.
5. Recommendation: Provide additional practice in Python.
6. Recommendation: Follow up with 1 student(s) below 75% attendance.

## **Code 13: Export Final Results to CSV**

In [39]:
# ================================================================
# CODE 13: EXPORT FINAL RESULTS
# ================================================================

OUTPUT_FILE = "student_performance_analysis.csv"

analysis.to_csv(OUTPUT_FILE, index=False)

print("Analysis exported successfully:", OUTPUT_FILE)

try:
    from google.colab import files
    files.download(OUTPUT_FILE)
except ImportError:
    print("Output saved in the current working directory.")

Analysis exported successfully: student_performance_analysis.csv

## **Code 14: Project Completion Message**

###================================================================
### CODE 14: PROJECT COMPLETION
###================================================================

STUDENT PERFORMANCE ANALYTICS SYSTEM COMPLETED

1. Dataset loaded and validated.
2. Student totals, averages, grades, and results calculated.
3. Subject-wise analysis completed.
4. Top-performing students identified.
5. Department-wise analysis completed.
6. Grade distribution and attendance analyzed.
7. NumPy calculations completed.
8. Final CSV file generated.

Thank you!